begin;
select plan(16);
select has_table('public','agent_definitions');
select has_table('public','agent_versions');
select has_table('public','agent_version_tools');
select has_table('public','agent_tool_catalog');
select has_column('public','agent_definitions','current_version_id');
select has_function('public','list_current_agents',array['integer']);
select has_function('public','create_current_agent',array['text','text','text','text','uuid','integer','uuid']);
select has_function('public','create_current_agent_version',array['uuid','text','text','text','jsonb','jsonb','text[]','text[]','jsonb','jsonb','uuid']);
select has_function('public','publish_current_agent_version',array['uuid','uuid','uuid']);
select policies_are('public','agent_versions',array[]::text[]);
select policies_are('public','agent_version_tools',array[]::text[]);
select policies_are('public','agent_tool_catalog',array[]::text[]);
select col_is_unique('public','agent_versions',array['tenant_id','agent_id','revision']);
select col_is_unique('public','agent_version_tools',array['agent_version_id','tool_code']);
select has_trigger('public','agent_versions','agent_versions_immutable');
select has_trigger('public','agent_version_tools','agent_version_tools_immutable');
select * from finish();
rollback;
