begin;
select plan(42);
select has_table('public','ai_rate_limit_windows');
select has_table('public','ai_rate_limit_receipts');
select has_table('public','ai_runtime_invocations');
select has_column('public','ai_runtime_invocations','request_id');
select has_column('public','ai_runtime_invocations','cost_amount');
select has_function('public','consume_ai_rate_limit',array['uuid','uuid','bigint','uuid','text','integer','integer','uuid']);
select has_function('public','start_ai_runtime_invocation',array['uuid','uuid','bigint','uuid','uuid','text','text','timestamp with time zone']);
select has_function('public','finalize_ai_runtime_invocation',array['uuid','uuid','bigint','uuid','uuid','text','integer','integer','numeric','text','timestamp with time zone']);
select policies_are('public','ai_rate_limit_windows',array[]::text[]);
select policies_are('public','ai_rate_limit_receipts',array[]::text[]);
select policies_are('public','ai_runtime_invocations',array['ai_runtime_self_select']);
select col_is_unique('public','ai_runtime_invocations',array['tenant_id','actor_member_id','request_id']);
select has_table('public','ai_conversations');
select has_table('public','ai_messages');
select has_table('public','ai_tool_calls');
select has_function('public','list_current_ai_conversations',array['integer']);
select has_function('public','list_current_ai_messages',array['uuid','integer']);
select has_function('public','create_ai_conversation',array['text','uuid','uuid']);
select has_function('public','append_ai_user_message',array['uuid','text','uuid','uuid']);
select has_function('public','archive_ai_conversation',array['uuid','integer','uuid']);
select has_table('public','ai_runtime_budgets');
select has_table('public','ai_runtime_queue');
select has_table('public','ai_runtime_budget_reservations');
select has_table('public','ai_runtime_queue_commands');
select has_table('public','ai_human_confirmations');
select has_table('public','ai_high_risk_executions');
select has_table('public','ai_human_takeover_queue');
select has_table('public','ai_evaluation_cases');
select has_function('public','confirm_current_ai_action',array['text','text','text','integer','uuid']);
select has_function('public','claim_ai_human_confirmation',array['uuid','uuid','bigint','uuid','uuid','text','text','text']);
select has_function('public','complete_ai_high_risk_execution',array['uuid','uuid','boolean','jsonb','text']);
select has_function('public','claim_ai_runtime_queue_job',array['integer']);
select has_function('public','enqueue_ai_runtime_job',array['uuid','uuid','bigint','uuid','uuid','text','jsonb','integer','integer','timestamp with time zone','integer','text[]','bigint','numeric']);
select has_function('public','complete_ai_runtime_queue_job',array['uuid','uuid','text','jsonb','text','bigint','numeric','integer']);
select has_function('public','cancel_ai_runtime_job',array['uuid','uuid','bigint','uuid','uuid','uuid']);
select has_function('public','retry_ai_runtime_job',array['uuid','uuid','bigint','uuid','uuid','uuid']);
select has_function('public','purge_expired_ai_runtime_records',array['integer']);
select policies_are('public','ai_runtime_budgets',array[]::text[]);
select policies_are('public','ai_runtime_budget_reservations',array[]::text[]);
select policies_are('public','ai_runtime_queue_commands',array[]::text[]);
select policies_are('public','ai_runtime_queue',array['ai_runtime_queue_self_read']);
select col_is_unique('public','ai_runtime_queue',array['tenant_id','actor_member_id','request_id']);
select * from finish();
rollback;
