import fs from"node:fs";import path from"node:path";import{describe,expect,it,vi}from"vitest";import{handleAgentKillSwitch}from"@/features/agents/agent-kill-switch";import{executiveWorkspaceSession}from"@/test/workspace-session-test-utils";
const requestId="11111111-1111-4111-8111-111111111111";const admin={...executiveWorkspaceSession,permissionCodes:[...executiveWorkspaceSession.permissionCodes,"agent.runtime.kill" as const]};
describe("tenant Agent Kill Switch",()=>{
 it("returns the current tenant control only to emergency-stop operators",async()=>{const rpc=vi.fn().mockResolvedValue({data:{enabled:false,reason:"",version:1,updatedAt:null},error:null});const response=await handleAgentKillSwitch(new Request("https://q.test",{method:"GET"}),{loadSession:async()=>admin,rpc});expect(response.status).toBe(200);expect(rpc).toHaveBeenCalledWith("get_current_tenant_agent_runtime_control",{});});
 it("enforces lifecycle, allowlists, limits, loop detection and cooperative cancellation in the database",()=>{const sql=fs.readFileSync(path.join(process.cwd(),"supabase/migrations/202608300015_agent_runtime_governance.sql"),"utf8").toLowerCase();for(const marker of["agent_runtime_tool_allowlists","agent_runtime_data_allowlists","agent_step_limit","agent_loop_detected","agent_concurrency_limit","cancel_requested_at","tenant_kill_switch"])expect(sql).toContain(marker);});
 it("hides the tenant control from users without the emergency permission",async()=>{const rpc=vi.fn();const response=await handleAgentKillSwitch(new Request("https://q.test",{method:"POST",body:"{}"}),{loadSession:async()=>executiveWorkspaceSession,rpc});expect(response.status).toBe(404);expect(rpc).not.toHaveBeenCalled();});
 it("atomically enables the tenant switch with an audited reason",async()=>{const rpc=vi.fn().mockResolvedValue({data:{enabled:true,version:2},error:null});const response=await handleAgentKillSwitch(new Request("https://q.test",{method:"POST",headers:{"idempotency-key":requestId},body:JSON.stringify({enabled:true,reason:"检测到异常外部调用，紧急停止"})}),{loadSession:async()=>admin,rpc});expect(response.status).toBe(200);expect(rpc).toHaveBeenCalledWith("set_current_tenant_agent_kill_switch",{p_enabled:true,p_reason:"检测到异常外部调用，紧急停止",p_request_id:requestId});});
 it("maps cross-tenant or stale authority to a non-disclosing 404",async()=>{const rpc=vi.fn().mockResolvedValue({data:null,error:{code:"P0002"}});const response=await handleAgentKillSwitch(new Request("https://q.test",{method:"POST",body:JSON.stringify({enabled:false,reason:"管理员确认风险解除，恢复运行"})}),{loadSession:async()=>admin,rpc,createRequestId:()=>requestId});expect(response.status).toBe(404);});
});
