import fs from"node:fs";import path from"node:path";import{describe,expect,it,vi}from"vitest";
import{handleAgentRuns}from"@/features/agents/agent-runtime-handler";import{executiveWorkspaceSession}from"@/test/workspace-session-test-utils";
const agentId="11111111-1111-4111-8111-111111111111",requestId="22222222-2222-4222-8222-222222222222",runId="33333333-3333-4333-8333-333333333333";
describe("append-only Agent runs",()=>{
 it("pins the published version and keeps steps append-only",()=>{const sql=fs.readFileSync(path.join(process.cwd(),"supabase/migrations/202608300014_agent_execution_pinning.sql"),"utf8").toLowerCase();expect(sql).toContain("agent_version_id");expect(sql).toContain("agent_invocations_request_uidx");expect(sql).toContain("agent_invocation_steps_append_only");expect(sql).toContain("new.agent_version_id is distinct from definition.current_version_id");});
 it("executes through the real AI boundary then reloads the durable run",async()=>{const rpc=vi.fn().mockResolvedValueOnce({data:{items:[]},error:null}).mockResolvedValueOnce({data:{items:[{id:runId,requestId,status:"succeeded",outputSummary:"完成"}]},error:null});const invoke=vi.fn().mockResolvedValue(Response.json({choices:[{message:{content:"完成"}}]}));const response=await handleAgentRuns(new Request("https://q.test/api/workstation/agents/x/runs",{method:"POST",headers:{"content-type":"application/json","idempotency-key":requestId},body:JSON.stringify({input:{goal:"复盘项目"}})}),agentId,{loadSession:async()=>executiveWorkspaceSession,rpc,invoke});expect(response.status).toBe(201);expect(invoke).toHaveBeenCalledWith(expect.objectContaining({method:"POST"}));const forwarded=invoke.mock.calls[0][0] as Request;expect(forwarded.headers.get("idempotency-key")).toBe(requestId);expect(await forwarded.clone().json()).toMatchObject({agent_public_id:agentId,messages:[{role:"user",content:JSON.stringify({goal:"复盘项目"})}]});});
 it("returns a terminal idempotent run without calling the provider twice",async()=>{const existing={id:runId,requestId,status:"succeeded"};const rpc=vi.fn().mockResolvedValue({data:{items:[existing]},error:null});const invoke=vi.fn();const response=await handleAgentRuns(new Request("https://q.test",{method:"POST",headers:{"idempotency-key":requestId},body:JSON.stringify({input:"再次运行"})}),agentId,{loadSession:async()=>executiveWorkspaceSession,rpc,invoke});expect(response.status).toBe(200);expect(await response.json()).toMatchObject({run:existing,alreadyExists:true});expect(invoke).not.toHaveBeenCalled();});
 it("fails closed if provider work is not followed by a durable invocation",async()=>{const rpc=vi.fn().mockResolvedValue({data:{items:[]},error:null});const response=await handleAgentRuns(new Request("https://q.test",{method:"POST",body:JSON.stringify({input:"运行"})}),agentId,{loadSession:async()=>executiveWorkspaceSession,rpc,invoke:async()=>Response.json({ok:true}),createRequestId:()=>requestId});expect(response.status).toBe(503);});
});
