import fs from"node:fs";import path from"node:path";import{describe,expect,it,vi}from"vitest";
import{handleOrchestrationCollection,validateOrchestrationGraph}from"@/features/agents/orchestration-handler";import{executiveWorkspaceSession}from"@/test/workspace-session-test-utils";
const a="11111111-1111-4111-8111-111111111111",b="22222222-2222-4222-8222-222222222222",requestId="33333333-3333-4333-8333-333333333333";const manager={...executiveWorkspaceSession,permissionCodes:[...executiveWorkspaceSession.permissionCodes,"agent.orchestrate" as const]};
describe("Agent orchestration",()=>{
 it("topologically sorts a connected compatible DAG",()=>{expect(validateOrchestrationGraph([{key:"research",agentVersionId:a,outputContract:"brief"},{key:"write",agentVersionId:b,inputContract:"brief"}],[{from:"research",to:"write"}])).toEqual({ok:true,order:["research","write"]});});
 it("rejects cycles, disconnected outputs and incompatible contracts",()=>{const nodes=[{key:"a",agentVersionId:a,outputContract:"a"},{key:"b",agentVersionId:b,inputContract:"b",outputContract:"b"}];expect(validateOrchestrationGraph(nodes,[{from:"a",to:"b"},{from:"b",to:"a"}])).toEqual({ok:false,code:"orchestration_contract_mismatch"});expect(validateOrchestrationGraph(nodes,[])).toEqual({ok:false,code:"orchestration_disconnected"});expect(validateOrchestrationGraph(nodes,[{from:"a",to:"b"}])).toEqual({ok:false,code:"orchestration_contract_mismatch"});expect(validateOrchestrationGraph(nodes.map(node=>({...node,inputContract:undefined,outputContract:undefined})),[{from:"a",to:"b"},{from:"b",to:"a"}])).toEqual({ok:false,code:"orchestration_cycle"});});
 it("pins published Agent versions and protects published graph rows",()=>{const sql=fs.readFileSync(path.join(process.cwd(),"supabase/migrations/202608300013_agent_orchestration.sql"),"utf8").toLowerCase();expect(sql).toContain("version.lifecycle='published'");expect(sql).toContain("orchestration_contract_mismatch");expect(sql).toContain("agent_orchestration_nodes_immutable");expect(sql).toContain("for update");});
 it("persists only a validated graph for an authorized orchestrator",async()=>{const rpc=vi.fn().mockResolvedValue({data:{orchestrationId:a,versionId:b,revision:1},error:null});const response=await handleOrchestrationCollection(new Request("https://q.test",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:"review_flow",name:"复盘工作流",nodes:[{key:"research",agentVersionId:a,outputContract:"brief"},{key:"write",agentVersionId:b,inputContract:"brief"}],edges:[{from:"research",to:"write"}]})}),{loadSession:async()=>manager,rpc,createRequestId:()=>requestId});expect(response.status).toBe(201);expect(rpc).toHaveBeenCalledWith("create_current_agent_orchestration",expect.objectContaining({p_nodes:[{key:"research",agentVersionId:a},{key:"write",agentVersionId:b}],p_request_id:requestId}));});
 it("blocks an ordinary employee before persistence",async()=>{const rpc=vi.fn();const response=await handleOrchestrationCollection(new Request("https://q.test",{method:"POST",body:"{}"}),{loadSession:async()=>executiveWorkspaceSession,rpc});expect(response.status).toBe(403);expect(rpc).not.toHaveBeenCalled();});
});
