import {randomUUID} from "node:crypto";

import {getWorkspaceSession} from "@/features/auth/workspace-session";
import type {WorkspaceSession} from "@/features/auth/workspace-session-types";
import {getSupabaseServerClient} from "@/lib/supabase/server";

export type OrchestrationNode={key:string;agentVersionId:string;inputContract?:string;outputContract?:string};
export type OrchestrationEdge={from:string;to:string};
export type OrchestrationValidation={ok:true;order:string[]}|{ok:false;code:"orchestration_invalid"|"orchestration_cycle"|"orchestration_disconnected"|"orchestration_contract_mismatch"};

export function validateOrchestrationGraph(nodes:readonly OrchestrationNode[],edges:readonly OrchestrationEdge[]):OrchestrationValidation{
  if(nodes.length<1||nodes.length>50||edges.length>200)return{ok:false,code:"orchestration_invalid"};
  const byKey=new Map(nodes.map(node=>[node.key,node]));if(byKey.size!==nodes.length||nodes.some(node=>!node.key||!node.agentVersionId))return{ok:false,code:"orchestration_invalid"};
  const edgeKeys=new Set<string>();const outgoing=new Map<string,string[]>();const incoming=new Map(nodes.map(node=>[node.key,0]));const undirected=new Map(nodes.map(node=>[node.key,[] as string[]]));
  for(const edge of edges){const key=`${edge.from}\u0000${edge.to}`;if(!byKey.has(edge.from)||!byKey.has(edge.to)||edge.from===edge.to||edgeKeys.has(key))return{ok:false,code:"orchestration_invalid"};edgeKeys.add(key);outgoing.set(edge.from,[...(outgoing.get(edge.from)??[]),edge.to]);incoming.set(edge.to,(incoming.get(edge.to)??0)+1);undirected.get(edge.from)?.push(edge.to);undirected.get(edge.to)?.push(edge.from);const source=byKey.get(edge.from);const target=byKey.get(edge.to);if(source?.outputContract&&target?.inputContract&&source.outputContract!==target.inputContract)return{ok:false,code:"orchestration_contract_mismatch"};}
  const queue=[...incoming].filter(([,count])=>count===0).map(([key])=>key).sort();const order:string[]=[];while(queue.length){const key=queue.shift()!;order.push(key);for(const target of outgoing.get(key)??[]){const count=(incoming.get(target)??0)-1;incoming.set(target,count);if(count===0){queue.push(target);queue.sort();}}}if(order.length!==nodes.length)return{ok:false,code:"orchestration_cycle"};
  const seen=new Set<string>();const pending=[nodes[0].key];while(pending.length){const key=pending.pop()!;if(seen.has(key))continue;seen.add(key);pending.push(...(undirected.get(key)??[]));}if(seen.size!==nodes.length)return{ok:false,code:"orchestration_disconnected"};
  return{ok:true,order};
}

type RpcError={code?:string}|null;type RpcResult={data:unknown;error:RpcError};export type OrchestrationDependencies={loadSession:()=>Promise<WorkspaceSession|null>;rpc:(name:string,args:Record<string,unknown>)=>Promise<RpcResult>;createRequestId?:()=>string};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const CODE=/^[a-z][a-z0-9_]{1,79}$/;
function record(value:unknown):Record<string,unknown>|null{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:null;}function json(value:unknown,status=200){return Response.json(value,{status,headers:{"Cache-Control":"no-store"}});}function statusFor(error:RpcError){return error?.code==="42501"?403:error?.code==="P0002"?404:["23505","55000"].includes(error?.code??"")?409:error?.code==="22023"?422:503;}async function defaults():Promise<OrchestrationDependencies>{const client=await getSupabaseServerClient();return{loadSession:getWorkspaceSession,rpc:async(name,args)=>await client.rpc(name,args) as RpcResult};}

export async function handleOrchestrationCollection(request:Request,provided?:OrchestrationDependencies){const deps=provided??await defaults();const session=await deps.loadSession();if(!session)return json({error:"unauthenticated"},401);if(!session.permissionCodes.includes("agent.orchestrate"))return json({error:"forbidden"},403);if(request.method==="GET"){const result=await deps.rpc("list_current_agent_orchestrations",{p_limit:100});return result.error?json({error:"orchestration_unavailable"},statusFor(result.error)):json(record(result.data)??{items:[]});}if(request.method!=="POST")return json({error:"method_not_allowed"},405);const raw=await request.text();if(Buffer.byteLength(raw,"utf8")>65_536)return json({error:"invalid_request"},400);let value:Record<string,unknown>|null=null;try{value=record(JSON.parse(raw));}catch{/* invalid */}const code=String(value?.code??"");const name=typeof value?.name==="string"?value.name.trim():"";const description=typeof value?.description==="string"?value.description.trim():"";const nodes=Array.isArray(value?.nodes)?value.nodes.map(record):[];const edges=Array.isArray(value?.edges)?value.edges.map(record):[];const parsedNodes=nodes.every(Boolean)?nodes.map(node=>({key:String(node!.key??""),agentVersionId:String(node!.agentVersionId??""),inputContract:typeof node!.inputContract==="string"?node!.inputContract:undefined,outputContract:typeof node!.outputContract==="string"?node!.outputContract:undefined})):[];const parsedEdges=edges.every(Boolean)?edges.map(edge=>({from:String(edge!.from??""),to:String(edge!.to??"")})):[];const validation=validateOrchestrationGraph(parsedNodes,parsedEdges);const key=request.headers.get("idempotency-key")?.toLowerCase()??deps.createRequestId?.()??randomUUID();if(!CODE.test(code)||name.length<2||name.length>120||description.length>2000||parsedNodes.some(node=>!UUID.test(node.agentVersionId))||!validation.ok||!UUID.test(key))return json({error:validation.ok?"invalid_request":validation.code},400);const result=await deps.rpc("create_current_agent_orchestration",{p_code:code,p_name:name,p_description:description,p_nodes:parsedNodes.map(({key,agentVersionId})=>({key,agentVersionId})),p_edges:parsedEdges,p_request_id:key});const status=result.error?statusFor(result.error):201;return json(result.error?{error:status===403?"forbidden":status===404?"not_found":status===409?"conflict":status===422?"invalid_request":"orchestration_unavailable"}:{...record(result.data),requestId:key,order:validation.order},status);}

export async function handleOrchestrationPublish(request:Request,orchestrationId:string,provided?:OrchestrationDependencies){if(!UUID.test(orchestrationId))return json({error:"not_found"},404);const deps=provided??await defaults();const session=await deps.loadSession();if(!session)return json({error:"unauthenticated"},401);if(!session.permissionCodes.includes("agent.orchestrate"))return json({error:"forbidden"},403);if(request.method!=="POST")return json({error:"method_not_allowed"},405);let value:Record<string,unknown>|null=null;try{value=record(JSON.parse(await request.text()));}catch{/* invalid */}const versionId=String(value?.versionId??"");const key=request.headers.get("idempotency-key")?.toLowerCase()??deps.createRequestId?.()??randomUUID();if(!UUID.test(versionId)||!UUID.test(key))return json({error:"invalid_request"},400);const result=await deps.rpc("publish_current_agent_orchestration",{p_orchestration_public_id:orchestrationId,p_version_public_id:versionId,p_request_id:key});const status=result.error?statusFor(result.error):200;return json(result.error?{error:status===409?"conflict":status===422?"invalid_request":"orchestration_unavailable"}:{...record(result.data),requestId:key},status);}
