import Image from "next/image";
import { CalendarDays, Languages, Moon, UserRound } from "lucide-react";

import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Toggle } from "@/components/ui/toggle";
import type { SettingsState } from "@/features/settings/settings-types";

export function PersonalSettings({ profile, value, onChange }: { profile: SettingsState["profile"]; value: SettingsState["personal"]; onChange: (value: SettingsState["personal"]) => void }) {
  const patch = (next: Partial<SettingsState["personal"]>) => onChange({ ...value, ...next });
  return <section aria-labelledby="personal-settings-title"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-chart-3/10 text-chart-3"><UserRound className="size-5" /></span><div><h2 id="personal-settings-title" className="text-xl font-semibold">个人设置</h2><p className="text-sm text-muted-foreground">身份资料来自飞书；这里只保存当前账号的显示偏好。</p></div></div><div className="mt-5 grid gap-4 lg:grid-cols-[260px_1fr]"><div className="rounded-2xl border bg-background/60 p-5 text-center"><Avatar className="mx-auto size-20">{profile.avatarUrl ? <Image src={profile.avatarUrl} alt="个人头像" fill unoptimized className="rounded-full object-cover" /> : <AvatarFallback className="bg-primary text-xl text-primary-foreground">{profile.name.slice(0, 1)}</AvatarFallback>}</Avatar><p className="mt-3 font-semibold">{profile.name}</p><p className="text-xs text-muted-foreground">{profile.email || "未同步企业邮箱"}</p><p className="mt-3 rounded-full bg-muted px-3 py-1 text-xs">飞书身份只读</p></div><div className="grid content-start gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">界面语言<Select value={value.language} onValueChange={(language) => patch({ language })}><SelectTrigger aria-label="界面语言"><Languages className="size-4" /><SelectValue /></SelectTrigger><SelectContent><SelectItem value="zh-cn">简体中文</SelectItem><SelectItem value="en">English</SelectItem></SelectContent></Select></label><label className="grid gap-2 text-sm font-medium">日期格式<Select value={value.dateFormat} onValueChange={(dateFormat) => patch({ dateFormat })}><SelectTrigger aria-label="日期格式"><CalendarDays className="size-4" /><SelectValue /></SelectTrigger><SelectContent><SelectItem value="yyyy-mm-dd">YYYY-MM-DD</SelectItem><SelectItem value="yyyy-mm-dd-cn">YYYY年MM月DD日</SelectItem></SelectContent></Select></label><div className="flex min-h-15 items-center gap-3 rounded-2xl border px-4 sm:col-span-2"><Moon className="size-5 text-primary" /><div className="min-w-0 flex-1"><p className="font-medium">深色模式跟随系统</p><p className="text-xs text-muted-foreground">此偏好会跨设备同步。</p></div><Toggle pressed={value.followSystemTheme} onPressedChange={(followSystemTheme) => patch({ followSystemTheme })} aria-label="深色模式跟随系统" className="h-7 w-12 justify-start rounded-full bg-muted p-1 data-[state=on]:justify-end data-[state=on]:bg-primary"><span className="size-5 rounded-full bg-background shadow-sm" /></Toggle></div></div></div></section>;
}
