import type { SettingsState } from "@/features/settings/settings-types";

function record(value: unknown): Record<string, unknown> | null { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null; }
function strings(value: unknown, keys: readonly string[]) { const item = record(value); return item && keys.every((key) => typeof item[key] === "string") ? item : null; }
function booleans(value: unknown, keys: readonly string[]) { const item = record(value); return item && keys.every((key) => typeof item[key] === "boolean") ? item : null; }

export function parseSettingsState(value: unknown): SettingsState | null {
  const root = record(value); const organization = strings(root?.organization, ["name", "shortName", "logoUrl", "timezone", "language", "foundedDate", "workWeekStart"]); const profile = strings(root?.profile, ["name", "email", "avatarUrl", "source"]); const personalText = strings(root?.personal, ["language", "dateFormat"]); const personalBool = booleans(root?.personal, ["followSystemTheme"]); const notifications = booleans(root?.notifications, ["inApp", "email", "dailyDigest"]); const schedulerText = strings(root?.scheduler, ["workdayStart", "workdayEnd"]); const scheduler = record(root?.scheduler); const versions = record(root?.versions);
  if (!root || !organization || !profile || profile.source !== "feishu" || !personalText || !personalBool || !notifications || !schedulerText || !scheduler || !versions || typeof root.canManage !== "boolean" || typeof root.asOf !== "string" || !["organization", "personal", "notifications", "scheduler"].every((key) => Number.isSafeInteger(versions[key]) && Number(versions[key]) >= 0) || !Number.isSafeInteger(scheduler.defaultPlanDays) || !Number.isSafeInteger(scheduler.maxDailyHours)) return null;
  return { organization: organization as SettingsState["organization"], profile: profile as unknown as SettingsState["profile"], personal: { language: String(personalText.language), dateFormat: String(personalText.dateFormat), followSystemTheme: Boolean(personalBool.followSystemTheme) }, notifications: notifications as unknown as SettingsState["notifications"], scheduler: { workdayStart: String(schedulerText.workdayStart), workdayEnd: String(schedulerText.workdayEnd), defaultPlanDays: Number(scheduler.defaultPlanDays), maxDailyHours: Number(scheduler.maxDailyHours) }, versions: { organization: Number(versions.organization), personal: Number(versions.personal), notifications: Number(versions.notifications), scheduler: Number(versions.scheduler) }, canManage: root.canManage, asOf: root.asOf };
}
