import { describe, expect, it, vi } from "vitest";
import { handleWorkspaceSettings } from "@/features/settings/settings-command-handler";
import { executiveWorkspaceSession } from "@/test/workspace-session-test-utils";

const requestId = "11111111-1111-4111-8111-111111111111";
describe("workspace settings commands", () => {
  it("loads the current member and organization projection", async () => { const rpc = vi.fn().mockResolvedValue({ data: { canManage: false }, error: null }); const response = await handleWorkspaceSettings(new Request("https://q.test", { method: "GET" }), { loadSession: async () => executiveWorkspaceSession, rpc }); expect(response.status).toBe(200); expect(rpc).toHaveBeenCalledWith("current_workspace_settings", {}); });
  it("allows a member to persist personal preferences only for the current session", async () => { const rpc = vi.fn().mockResolvedValue({ data: { namespace: "personal", version: 2 }, error: null }); const response = await handleWorkspaceSettings(new Request("https://q.test", { method: "PUT", headers: { "content-type": "application/json", "idempotency-key": requestId }, body: JSON.stringify({ namespace: "personal", settings: { language: "zh-cn", dateFormat: "yyyy-mm-dd", followSystemTheme: true }, expectedVersion: 1 }) }), { loadSession: async () => executiveWorkspaceSession, rpc }); expect(response.status).toBe(200); expect(rpc).toHaveBeenCalledWith("update_current_workspace_settings", expect.objectContaining({ p_namespace: "personal", p_expected_version: 1, p_request_id: requestId })); });
  it("blocks enterprise updates without settings.manage before database access", async () => { const rpc = vi.fn(); const response = await handleWorkspaceSettings(new Request("https://q.test", { method: "PUT", body: JSON.stringify({ namespace: "organization", settings: {}, expectedVersion: 0 }) }), { loadSession: async () => executiveWorkspaceSession, rpc, createRequestId: () => requestId }); expect(response.status).toBe(403); expect(rpc).not.toHaveBeenCalled(); });
  it("maps optimistic version conflicts", async () => { const rpc = vi.fn().mockResolvedValue({ data: null, error: { code: "40001" } }); const response = await handleWorkspaceSettings(new Request("https://q.test", { method: "PUT", body: JSON.stringify({ namespace: "notifications", settings: { inApp: true, email: false, dailyDigest: false }, expectedVersion: 1 }) }), { loadSession: async () => executiveWorkspaceSession, rpc, createRequestId: () => requestId }); expect(response.status).toBe(409); expect(await response.json()).toEqual({ error: "version_conflict" }); });
});
