import { mockMembers, mockProjects } from "@/features/projects/mock-data";
import type { Customer } from "@/features/customers/customer-types";

export const customersMockData: readonly Customer[] = [
  { id: "customer-1", name: "星河科技有限公司", contact: { name: "张宇", phone: "138 **** 9921", email: "zhangyu@example.com", title: "信息化负责人" }, owner: mockMembers[1], status: "following", source: "consulting", industry: "technology", region: "华东地区", lastContactAt: "2026-08-05", nextFollowUpAt: "2026-08-08 10:00", dealProgress: 60, dealAmount: 680000, createdAt: "2026-08-01", relatedProjectIds: [mockProjects[0].id], activities: [{ id: "ca-1", content: "沟通了企业解决方案白皮书", createdAt: "10 分钟前" }] },
  { id: "customer-2", name: "未来智造集团", contact: { name: "李明", phone: "139 **** 1123", email: "liming@example.com", title: "数字化总监" }, owner: mockMembers[3], status: "proposal", source: "event", industry: "manufacturing", region: "华南地区", lastContactAt: "2026-08-04", nextFollowUpAt: "2026-08-09 14:00", dealProgress: 75, dealAmount: 920000, createdAt: "2026-07-18", relatedProjectIds: [mockProjects[1].id], activities: [{ id: "ca-2", content: "下载了产品功能介绍文档", createdAt: "35 分钟前" }] },
  { id: "customer-3", name: "云启信息技术有限公司", contact: { name: "陈静", phone: "137 **** 5566", email: "chenjing@example.com", title: "产品副总裁" }, owner: mockMembers[0], status: "lead", source: "referral", industry: "technology", region: "华北地区", lastContactAt: "2026-08-03", nextFollowUpAt: "2026-08-07 09:30", dealProgress: 30, dealAmount: 460000, createdAt: "2026-08-03", relatedProjectIds: [], activities: [{ id: "ca-3", content: "完成首次需求沟通", createdAt: "1 小时前" }] },
  { id: "customer-4", name: "锐思数据服务有限公司", contact: { name: "赵敏", phone: "135 **** 7766", email: "zhaomin@example.com", title: "客户成功总监" }, owner: mockMembers[1], status: "following", source: "event", industry: "finance", region: "华东地区", lastContactAt: "2026-08-02", nextFollowUpAt: "2026-08-10 15:00", dealProgress: 50, dealAmount: 760000, createdAt: "2026-06-20", relatedProjectIds: [mockProjects[2].id], activities: [{ id: "ca-4", content: "提交了新的需求反馈", createdAt: "2 小时前" }] },
  { id: "customer-5", name: "博远软件股份有限公司", contact: { name: "周强", phone: "136 **** 8899", email: "zhouqiang@example.com", title: "运营负责人" }, owner: mockMembers[3], status: "won", source: "consulting", industry: "technology", region: "西南地区", lastContactAt: "2026-07-30", nextFollowUpAt: "2026-08-15 11:00", dealProgress: 100, dealAmount: 1180000, createdAt: "2026-05-12", relatedProjectIds: [mockProjects[3].id], activities: [{ id: "ca-5", content: "完成项目交付验收", createdAt: "昨天" }] },
  { id: "customer-6", name: "创想未来科技有限公司", contact: { name: "孙凯", phone: "138 **** 3344", email: "sunkai@example.com", title: "市场负责人" }, owner: mockMembers[0], status: "negotiating", source: "referral", industry: "retail", region: "华中地区", lastContactAt: "2026-07-29", nextFollowUpAt: "2026-08-11 16:00", dealProgress: 80, dealAmount: 540000, createdAt: "2026-06-08", relatedProjectIds: [mockProjects[1].id], activities: [{ id: "ca-6", content: "确认了合同报价范围", createdAt: "昨天 16:45" }] },
];
